# Site settings
title: Javier Quinteros' home page
emailW: javier (at) gfz.de
emailP: javier (at) quinteros.eu
description: > # this means to ignore newlines until "baseurl:"
  Personal page where you can find some information about my work, interests
  and some short posts written by me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://javiquinte.github.io" # the base hostname & protocol for your site

github_username: javiquinte
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
# remote_theme: mmistakes/minimal-mistakes
remote_theme: "mmistakes/minimal-mistakes@4.27.1"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europa/Berlin

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name   : "Javier Quinteros"
  avatar : "./img/javier-2020.jpeg"
  bio    : "Scientist, football fan of San Lorenzo, father of two."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://javier.quinteros.eu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/javiquinte"
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/quinteros.eu"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.uy/@javiquinte"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# stackoverflow: 2705572
