# Site settings
title: Javier Quinteros' home page
author: "Javier Quinteros"
emailW: javier (at) gfz-potsdam.de
emailP: javier (at) quinteros.eu
description: > # this means to ignore newlines until "baseurl:"
  Personal page where you can find some information about my work, interests
  and some short posts written by me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://javiquinte.github.io" # the base hostname & protocol for your site
instagram: aboutjavier
twitter: QuinteJavi
github:  javiquinte
stackoverflow: users/2705572/javier
avatar:  javier.jpg

# Build settings
markdown: kramdown
timezone: Europa/Berlin

theme: jekyll-theme-modernist
